# Generated by Django 3.0.4 on 2020-04-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_card_fraud_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='account_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=100)),
                ('account_balance', models.CharField(max_length=100)),
                ('cvv_code', models.CharField(max_length=100)),
                ('exp_date', models.DateField()),
                ('card_no', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
