# Generated by Django 3.0.4 on 2020-04-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_card_fraud_app', '0002_account_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=20)),
            ],
        ),
    ]
