# Generated by Django 3.0.4 on 2020-04-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_card_fraud_app', '0003_transaction_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='security_check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('secu_ques1', models.CharField(max_length=100)),
                ('secu_ques2', models.CharField(max_length=100)),
                ('secu_ques3', models.CharField(max_length=100)),
                ('secu_ques4', models.CharField(max_length=100)),
                ('answer1', models.CharField(max_length=100)),
                ('answer2', models.CharField(max_length=100)),
                ('answer3', models.CharField(max_length=100)),
                ('answer4', models.CharField(max_length=100)),
            ],
        ),
    ]
