# Generated by Django 3.0.4 on 2020-04-24 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_card_fraud_app', '0008_auto_20200423_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_details',
            name='bank_name',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
