# Generated by Django 3.0.4 on 2020-06-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_card_fraud_app', '0010_account_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction_details',
            name='card_no',
        ),
        migrations.RemoveField(
            model_name='transaction_details',
            name='location',
        ),
        migrations.RemoveField(
            model_name='transaction_details',
            name='time',
        ),
        migrations.AddField(
            model_name='transaction_details',
            name='acct_num',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction_details',
            name='bank_name',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction_details',
            name='branch',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction_details',
            name='cus_name',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction_details',
            name='email',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction_details',
            name='phone',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction_details',
            name='amount',
            field=models.CharField(max_length=20),
        ),
    ]
