# Generated by Django 3.0.4 on 2020-06-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_card_fraud_app', '0011_auto_20200628_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_details',
            name='customer_id',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction_details',
            name='result',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
