# Generated by Django 3.0.4 on 2020-06-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_card_fraud_app', '0013_transaction_details_last_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_details',
            name='last_transaction',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
