# Generated by Django 3.0.4 on 2020-06-29 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit_card_fraud_app', '0014_auto_20200629_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction_details',
            name='last_transaction',
        ),
    ]
